## Bài tập 2

Câu 1: Hãy sử dụng numpy để giải các phương trình sau:

- Vấn đề 1 (Problem 1): Tìm điểm giao giữa hai đường thẳng trong $\mathbb{R}^2$.

- Vấn đề 2 (Problem 2): Tìm giao điểm giữa ba mặt phẳng trong $\mathbb{R}^3$.

- Vấn đề 3 (Problem 3): Tìm các hệ số đa thức để đa thức thỏa các nghiệm.

- Vấn đề 4 (Problem 4)Tìm các hệ đa thức khi phân rã để tính tích phân.



In [2]:
import numpy as np 

**vấn đề 1:** Tìm điểm giao giữa hai đường thẳng trong  $\mathbb{R}^{2} $.
$$ \begin{align*}
\begin{cases}
x -y &=-2 \\ 
2x + 3y &=6 
\end{cases}
\end{align*} $$

 

In [6]:
A = np.array ([[1,-1],[2,3]])
B= np.array ([-2,6])
x = np.linalg.solve(A,B)
print (x)

[0. 2.]


=> vậy X = (0,2)

**vấn đề 2:** Tìm giao điểm giữa ba mặt phẳng trong $\mathbb{R}^{3} $

$$ \begin {align*}
\begin {cases}
x - y & =2 \\
2x - y - z & = 3\\
x + y + z & 6
\end {cases}
\end {align*} $$

In [7]:
a = np.array ([[1,-1,0],[2,-1,-1],[1,1,1]])
b = np.array([2,3,6])
c = np.linalg.solve(a,b)
print(c)


[3. 1. 2.]


=> KQ : 3 , 1 ,2

**VẤN ĐỀ 3** tìm các hệ thức để đa thức thoả các nghiệm
$$ \begin {align*}
\begin {cases}
a + b + c & = 4\\
4a + 2b + c & = 3 \\
9a + 3b + c & = 4 
\end {cases}
\end {align*}$$

In [3]:
A = np.matrix([[1,1,1],[4,2,1],[9,3,1]])
b = np.matrix([[4],[3],[4]])
x =np.linalg.solve(A,b)
print(x)

[[ 1.]
 [-4.]
 [ 7.]]


=> Vậy hệ số đa thức thoả mãn các nghiệm: 1,-4,7

**vấn đề 4** Tìm các hệ đa thức khi phân rã để tính tích phân
$$ \int_{0}^{1} \frac{x(x-3)}{(x-1)^{2}(x+2)} dx $$


In [8]:
import numpy as np
from fractions import Fraction as f

A = np.matrix([[1, 0, 1], [1, 1, -2], [-2, 2, 1]])
b = np.matrix([[1], [-3], [0]])

x = np.linalg.solve(A, b)



print(x)


[[-0.11111111]
 [-0.66666667]
 [ 1.11111111]]


KQ: $\text{R(x)}=\frac{-1}{9(x-1)}+\frac{-2}{3(x-1)^2}+\frac{10}{9(x+2)}$

# **CÂU 2**  
*Viết các câu lệnh của Sympy để giải các phương trình ở Câu 1*

In [10]:
import sympy as sp 

**vấn đề 1.** Tìm điểm giao giữa hai đường thẳng trong  $\mathbb{R}^2$

$$ \begin {align*}
\begin {cases}
x & - & y & = & -2 \\
2x & + & 3y & = & 6
\end {cases}
\end {align*}$$


In [11]:
x = sp.Symbol('x')
y = sp.Symbol ('y')
res = sp.solve((x-y+2, 2*x+3*y-6),(x,y))
print(res)

{x: 0, y: 2}


**vấn đê 2** Tìm giao điểm giữa ba mặt phẳng trong $\mathbb {R}^{3}$
$$ \begin {align*}
\begin{cases}
x & - & y & = & 2\\
2x & - & y & - & z & = & 3\\
x & + & y & + & z & = & 6
\end {cases}
\end {align*}$$

In [12]:
x = sp.symbols('x')
y = sp.symbols('y')
z = sp.symbols('z')
res = sp.solve((x-y-0-2,2*x-y-z-3, x+y+z-6),(x,y,z))

print(res)

{x: 3, y: 1, z: 2}


**vấn đề 3** Tìm các hệ số đa thức để đa thức thoả các nghiệm 
$$\begin {align*}
\begin{cases}
a & + & b & + & c & = &4\\
4a & + & 2b & + & c & = &3\\
9a & + & 3b & + & c & = & 4
\end{cases} 
\end {align*}$$

In [13]:
a = sp.symbols ('a')
b = sp.symbols ('b')
c  = sp.symbols('c')
res = sp.solve ((a+b+c-4,4*a+2*b+c-3,9*a+3*b+c-4),(a,b,c))
print(res)

{a: 1, b: -4, c: 7}


**vấn đề 4** tìm các hệ đa thức khi phân rã để tính tích phân
$$ \int_{0}^{1} \frac{x(x-3)}{(x-2^2)(x=2)} dx $$

In [15]:
import sympy as sp
a = sp.Symbol('x')
b = sp.Symbol('y')
c = sp.Symbol('z')
res = sp.solve((x+z-1,x+y-2*z+3,-2*x+2*y+z),(x,y,z))
print(res)

{x: -1/9, y: -2/3, z: 10/9}


## **CÂU 3**
Tính luỹ thừa bậc k của ma trận $𝑭_k = \left( \begin{matrix} 1&1 \\ 1&0 \end{matrix}\right)^\text{k}$ và chứng minh ma trânh **F_k** chứa 3 phần tử của $\text{𝐹𝑖𝑏𝑜}_{𝑘+1}$, $\text{𝐹𝑖𝑏𝑜}_𝑘$ và $\text{𝐹𝑖𝑏𝑜}_{𝑘−1}$ của dãy Fibonacci (bắt đầu bằng 0 từ phần tử 0)

In [2]:
import numpy as np
def fibonacci_matrix_power(k):
    F = np.array([[1, 1], [1, 0]])
    F_k = np.linalg.matrix_power(F, k)
    return F_k

def fibonacci_sequence_elements(k):
    F_k = fibonacci_matrix_power(k)
    F_iplus1 = F_k[0, 0]
    F_i = F_k[1, 0]
    F_iminus1 = F_k[1, 1]
    return F_iplus1, F_i, F_iminus1

k = int (input("nhập phần tử thứ k: "))
F_iplus1, F_i, F_iminus1 = fibonacci_sequence_elements(k)

print(f"F_{k+1} =", F_iplus1)
print(f"F_{k} =", F_i)
print(f"F_{k-1} =", F_iminus1)


F_11 = 89
F_10 = 55
F_9 = 34
