## Bài 3: MA TRẬN VÀ HỆ PHƯƠNG TRÌNH TUYẾN TÍNH

In [5]:
from scipy import linalg 
import numpy as np
a = np.array([1,2,3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) 
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]]) 
A = np.matrix([[2,3],[1,4]])
B = np.asmatrix(b)
C = np.mat(np.random.random((10,5)))
D = np.mat([[4,3],[2,6]])
F = np.eye(3,k=1)
print(A)
print(B)
print(C)
print(D)
print(F)
F1 = np.eye(3,k=0)
print(F1)
F2 = np.eye(3,k=-1)
print(F2)
np.linalg.matrix_rank(C)
A.I # lấy ma trận nghịch đảo của A
linalg.inv(A)# lấy ma trận nghịch đảo của A
A.T # Chuyen vi ma tran
A.H # chuyển vị liên hợp
linalg.solve(A,b)
E =np.mat(a).T
print(E)
linalg.lstsq(E,E)
np.add(A,D)
np.subtract(A,D)
np.divide(A,D)
np.dot(A,D)
A@D
np.multiply(A,D)
np.vdot(A,D)#tinh tich vo huong
linalg.expm(A)# tinh e^A
linalg.logm(A)

[[2 3]
 [1 4]]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[0.79713554 0.10830118 0.05310507 0.99413686 0.599882  ]
 [0.31431656 0.18428725 0.44940733 0.35800437 0.01823843]
 [0.4181876  0.84073636 0.78612282 0.79048061 0.30876311]
 [0.67596549 0.57756811 0.35327594 0.99009074 0.76871464]
 [0.32856588 0.69068511 0.37392411 0.64558914 0.76222471]
 [0.38398683 0.07015433 0.36357198 0.87696876 0.3008109 ]
 [0.35191815 0.07541285 0.27196659 0.33924489 0.05516893]
 [0.8478231  0.22469939 0.77578287 0.14744528 0.76431201]
 [0.77429948 0.72788942 0.59470746 0.41072147 0.51423527]
 [0.15373285 0.76805414 0.8020874  0.22513995 0.1815532 ]]
[[4 3]
 [2 6]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[1]
 [2]
 [3]]


array([[0.40235948, 1.20707843],
       [0.40235948, 1.20707843]])

**Câu 1:** Viết bài thu hoạch (làm từng bước như bài toán ứng dụng 1) về nội dung:

Sinh viên hãy viết chương trình bằng Python hoặc sử dụng thư viện numpy/sympy để:

a. Tự chọn một ma trận khả nghịch 3x3. Sinh viên chứng minh ma trận đó khả nghịch (tồn
tại ma trận nghịch đảo)

b. Nhập họ và tên hoặc mã số sinh viên (của sinh viên).

c. Mã hóa họ và tên hoặc mã số sinh viên (của sinh viên).

d. Thực hiện giải mã với ma trận được chọn.


In [7]:
#a
import numpy as np
A = np.mat([[1,4,9],[9,1,3],[0,9,0]])
x = np.linalg.det(A)
# Kiểm tra xem giá trị định thức của ma trận A có khác 0 không? Nếu có thì
# A khả nghịch và tồn taị ma trận nghịch đảo và ngược lại.
if x == 0:
    print("Ma tran A khong kha nghich")
else:
    print("Ma tran A kha nghich")
    print("Ma tran nghich dao cua A la:")
    print(np.linalg.inv(A)) #A.I

Ma tran A kha nghich
Ma tran nghich dao cua A la:
[[-0.03846154  0.11538462  0.0042735 ]
 [ 0.          0.          0.11111111]
 [ 0.11538462 -0.01282051 -0.04985755]]


In [9]:
#b
sv = input("Nhập họ và tên hoặc mã số sinh viên: ")

#c
bangmahoa = {' ': 5, 'D': 11, 'I': 17, 'Ơ': 23, 'T': 29, 'U': 30, 'A': 6, 'Đ': 12, 'K': 18, 'Ô': 24,
            'Ă': 7, 'E': 13, 'L': 19, 'P': 25, 'Ư': 31, 'Â': 8, 'Ê': 14, 'M': 20, 'Q': 26, 'V': 32,
            'B': 9, 'G': 15, 'N': 21, 'R': 27, 'X': 33, 'C': 10, 'H': 16, 'O': 22, 'S': 28, 'Y': 34,
            '‘': 0, '`': 1, '?': 2, '~': 3, '.': 4}
input_str = sv
#Tạo ma trận từ đoạn tin
num_string = [bangmahoa[i] for i in input_str]
print("Chuỗi số tương ứng là: ", num_string)
#d
mat_size = 3
#Phân tích thành các ma trận con
B = [num_string[i:i+mat_size] for i in range(0,len(num_string),mat_size)]
print(B)
#Nhân các ma trận con với ma trận ban đầu để được ma trận mới
New=[row@A for row in B]
print("Ma trận mới: ")
print(New)
#Gộp các ma trận con thành ma trận hoàn chỉnh
Encoded=np.vstack(New)
print(Encoded)
#Thực hiện giải mã bằng cách nhân cho ma trận đã hóa với ma trận nghịch đảo của A
A1 = Encoded*(A.I)
print("Giải mã")
print(A1)

Nhập họ và tên hoặc mã số sinh viên:  TAN TAI


Chuỗi số tương ứng là:  [29, 6, 21, 5, 29, 6, 17]
[[29, 6, 21], [5, 29, 6], [17]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

Câu 2: Tính toán phân số từ liên phân số (continued fractions)
Với một phân số $\frac{p_n}{q_n}$$$$$được biểu diễn dưới dạng liên phân số như sau:
$$\frac{p_n}{q_n} = c_0 + \frac{1}{c_1+\frac{1}{c_2+...+\frac{1}{c_n}}}$$
Người ta chứng minh được rằng có một cách xác định $𝑝_𝑛$ và $𝑞_𝑛$ như sau:
$$\left(\begin{matrix}c_0&1\\1&0\end{matrix}\right)\left(\begin{matrix}c_1&1\\1&0\end{matrix}\right)...\left(\begin{matrix}c_n&1\\1&0\end{matrix}\right)=\left(\begin{matrix}p_n&q_{n-1}\\q_n&q_{n-1}\end{matrix}\right),n=0,1,2,...$$
a. Xây dựng chương trình tính 𝑝𝑛 và 𝑞𝑛 khi có danh sách 𝑛 giá trị $𝑐_0$, $𝑐_1$, … , $𝑐_𝑛$.

b. Hãy chứng minh điều trên.


In [15]:
#Tạo 1 danh sách gồm n phần tử ngẫu nhiên từ 0 đến 20
import numpy as np
import random
n = int(input("Nhập n: "))
A = [random.randint(0,21) for _ in range(n)]
print(A)
#tạo ma trận
def create_matrix(ds):
    ds_moi=[]
    for i in range(len(ds)):
        ds_moi.append(np.mat([[ds[i],1],[1,0]]))
    return ds_moi
newlist = create_matrix(A)
print(newlist)
#Hàm nhân ma trận
def multiply_matrices(matrix_list):
    result_matrix = None

    for matrix in matrix_list:
        if result_matrix is None:
            result_matrix = matrix
        else:
            result_matrix = np.dot(result_matrix, matrix)

    return result_matrix
tich=multiply_matrices(newlist)
print(tich)
# Lấy giá trị p_n và q_n
p_n = tich[0,0]
q_n = tich[1,0]
print(f"Giá trị p_n là {p_n}")
print(f"Giá trị q_n là {q_n}")

Nhập n: 2
[18, 3]
[matrix([[18,  1],
        [ 1,  0]]), matrix([[3, 1],
        [1, 0]])]
[[55 18]
 [ 3  1]]
Giá trị p_n là 55
Giá trị q_n là 3


Để chứng minh điều trên, chúng ta có thể sử dụng phương pháp quy nạp. Đặt ma trận được nhân là A và giả sử biểu thức trên đúng với n = k:

\$[ A_k = \begin{bmatrix} c_k & 1 \\ 1 & 0 \end{bmatrix} \begin{bmatrix} c_{k-1} & 1 \\ 1 & 0 \end{bmatrix} \dotsm \begin{bmatrix} c_1 & 1 \\ 1 & 0 \end{bmatrix} = \begin{bmatrix} p_k & p_{k-1} \\ q_k & q_{k-1} \end{bmatrix} \]$

Bây giờ, chúng ta sẽ chứng minh biểu thức cho n = k + 1:

\$[ A_{k+1} = \begin{bmatrix} c_{k+1} & 1 \\ 1 & 0 \end{bmatrix} \begin{bmatrix} p_k & p_{k-1} \\ q_k & q_{k-1} \end{bmatrix} \]$

\$[ A_{k+1} = \begin{bmatrix} c_{k+1}p_k + p_{k-1} & c_{k+1}p_{k-1} + p_k \\ c_{k+1}q_k + q_{k-1} & c_{k+1}q_{k-1} + q_k \end{bmatrix} \]$

Từ giả sử, chúng ta biết rằng \$( A_k = \begin{bmatrix} p_k & p_{k-1} \\ q_k & q_{k-1} \end{bmatrix} \)$. Đặt \$( p_{k+1} = c_{k+1}p_k + p_{k-1} \$) và \$( q_{k+1} = c_{k+1}q_k + q_{k-1} \$), chúng ta có thể thấy rằng \$( A_{k+1} = \begin{bmatrix} p_{k+1} & p_k \\ q_{k+1} & q_k \end{bmatrix} \$).

Do đó, biểu thức trên đúng với mọi n bằng cách sử dụng quy nạp.


In [ ]:
#b
hoten =  input("nhập ho va ten: ")
bangma = {' ': 5, 'A':6,'Ă':7,
          'Â':8,'B':9,'C':10,'D':11,'Đ':12,'E':13,'Ê':14,'G':15,'H':16,
          'I':17,'K':18,'L':19,'M':20,'N':21,'O':22,
          'Ơ':23,'Ô':24,'P':25,'Q':26,'R':27,'S':28,
          'T':29,'U':30,'Ư':31,'V':32,'X':33,'Y':34,
          'SẮC':0,'`':1,'?':2,'~':3,'.':4}
matrices = [np.array([bangma[char] for char in word]) for word in hoten.split()]
# print("ma trận giả định là: ")
# e = np.matrix([[1,-2,2],[-1,1,3],[1,-1,-4]])
for index, matrix in enumerate(matrices):
    print("Mã chuỗi số tương ứng với từ '{}' là:".format(hoten.split()[index]))
    print(matrix)
    print("mã chuỗi số tương ứng là: ")
    matrix-=5
    print(matrix)
    # encoded_matrix = np.matmul(matrix, e)
    # print("Mã hóa chuỗi là:")
    # print(encoded_matrix)