# BÀI 1: GIỚI THIỆU VỀ PYTHON VÀ CÁC THƯ VIỆN TÍNH TOÁN

## 1. Bài tập trên lớp

* Lệnh: >>> `mat1 = np.zeros([5,5])`

\begin{equation}
    \text {mat1 = }
    \begin{pmatrix}
      0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0 \\
      0 & 0 & 0 & 0 & 0 \\
    \end{pmatrix}
\end{equation}


In [2]:
import numpy as np

In [4]:
mat1 = np.zeros([5,5])
print(mat1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


* Lệnh: >>> `mat2 = np.ones([5,5])`

\begin{equation}
    \text{mat2 =} 
    \begin{pmatrix}
        1 & 1 & 1 & 1 & 1 \\
        1 & 1 & 1 & 1 & 1 \\
        1 & 1 & 1 & 1 & 1 \\
        1 & 1 & 1 & 1 & 1 \\
        1 & 1 & 1 & 1 & 1 \\
    \end{pmatrix}
\end{equation}

In [6]:
mat2 = np.ones([5,5])
print(mat2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


* Lệnh: >>> `mat3 = mat1 + 2* mat2`

\begin{equation}
    \text{mat3 = } 
    \begin{pmatrix}
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
    \end{pmatrix}
\end{equation}

In [8]:
mat3 = mat1 + 2* mat2
print(mat3)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


* Lệnh: >>> `mat4 = mat3`

* Lệnh: >>> `mat3[3][2] = 10`

\begin{equation}
    \text{mat3 =}
    \begin{pmatrix}
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 10 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
    \end{pmatrix}
\end{equation}

\begin{equation}
    \text{mat4 =} 
    \begin{pmatrix}
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 10 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
    \end{pmatrix}
\end{equation}

&rarr; **mat4 có thay đổi vì mat4 là được gán bằng với mat3**

In [13]:
mat4 = mat3
mat3[3][2] = 10
print(mat4, mat3, sep = "\n\n")

[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]

[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]


* Lệnh: >>> `mat5 = np.copy(mat3)`

* Lệnh: >>> `mat3[3][2] = 10`

\begin{equation}
    \text{mat3 =} 
    \begin{pmatrix}
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 10 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
    \end{pmatrix}
\end{equation}

\begin{equation}
    \text{mat4 =} 
    \begin{pmatrix}
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 10 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
    \end{pmatrix}
\end{equation}

\begin{equation}
    \text{mat5 =}
    \begin{pmatrix}
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
        2 & 2 & 2 & 2 & 2\\
    \end{pmatrix}
\end{equation}

&rarr; **mat3 thay đổi  thì chỉ có mat4 thay đổi còn mat5 không thay đổi. Bởi vì mat5 là một bản sao mới được tạo từ mat3 còn mat4 là được gán bằng với mat3.**

In [20]:
# Dua mat3 ve gia tri ban dau
mat3[3][2] = 2

mat5 = np.copy(mat3)
mat3[3][2] = 10
print(mat3, mat4, mat5, sep = "\n\n")

[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]

[[ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2.  2.  2.  2.]
 [ 2.  2. 10.  2.  2.]
 [ 2.  2.  2.  2.  2.]]

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


* Lệnh: >>> `mat6 = np.empty([4, 5])`

\begin{equation}
    \text{mat6 =} 
    \begin{pmatrix}
    9.01096911e-312 & 5.68175493e-322 & 0.00000000e+000 & 0.00000000e+000 &  9.34598924e-30\\]     [1.16095484e-0 & 8 2.87926253e-0 & 4 9.10434209e+2 &76 4.07177685e+2 & 
  1.29541836e+\\3    
 [1.17688986e &+136 6.74421134e &+217 3.99255467e &+252 1.00443548e & 5
  5.90148570\\+    5]
 [1.7653915 &6e+137 8.9316868 &9e+271 4.9813153 &6e+151 1.9492067 & 153
  3.242499\\e-086]]
    \end{pmatrix}
\end{equation}

In [22]:
mat6 = np.empty([4, 5])
print(mat6)

[[9.01096911e-312 5.68175493e-322 0.00000000e+000 0.00000000e+000
  9.34598924e-307]
 [1.16095484e-028 2.87926253e-014 9.10434209e+276 4.07177685e+223
  1.29541836e+132]
 [1.17688986e+136 6.74421134e+217 3.99255467e+252 1.00443548e-095
  5.90148570e+135]
 [1.76539156e+137 8.93168689e+271 4.98131536e+151 1.94920670e-153
  3.24249977e-086]]


* Lệnh: >>> `mat7 = np.identity(4)`

  \begin{equation}
    \text{mat7 =} 
    \begin{pmatrix}
      1 & 0 & 0 & 0\\
      0 & 1 & 0 & 0\\
      0 & 0 & 1 & 0\\
      0 & 0 & 0 & 1\\
    \end{pmatrix}
\end{equation}

In [24]:
mat7 = np.identity(4)
print(mat7)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


* Lệnh: >>> `mat8 = np.random.random([4,5])`


\begin{equation}
    \text{mat8 =} 
    \begin{pmatrix}
        0.39028529 & 0.75540465 & 0.01568219 & 0.29453656 & 0.91118005\\
        0.03844021 & 0.51781229 & 0.97992382 & 0.12070719 & 0.35404779\\
        0.07206803 & 0.84809791 & 0.49324525 & 0.92903231 & 0.81489341\\
        0.78460077 & 0.44073672 & 0.24756567 & 0.11936058 & 0.7039666\\
    \end{pmatrix}
\end{equation}

In [28]:
mat8 = np.rand([4,5])
print(mat8)

AttributeError: module 'numpy' has no attribute 'rand'

In [3]:
# mat8 = np.rand([4,5])
mat8 = np.random.random([4,5])
print(mat8)

[[0.39028529 0.75540465 0.01568219 0.29453656 0.91118005]
 [0.03844021 0.51781229 0.97992382 0.12070719 0.35404779]
 [0.07206803 0.84809791 0.49324525 0.92903231 0.81489341]
 [0.78460077 0.44073672 0.24756567 0.11936058 0.7039666 ]]


## 2. Bài tập về nhà

### Bài 1. Điểm môn học của một nhóm SV được cho như bên dưới:

| Sinh Viên| BT cá nhân | Báo cáo | Giữa kỳ | Cuối Kỳ |
|:--------:|:----------:|:-------:|:-------:|:-------:|
|     A    |      7     |    8    |    9    |    5    |
|     B    |      8     |    7    |    4    |    6    |
|     C    |      7     |    5    |    8    |    6    |
|     D    |      6     |    8    |    5    |    4    |
|     E    |      9     |    9    |    8    |    7    |
|     F    |     10     |    8    |    9    |    8    |

**Tỷ lệ % điểm:**

| BT cá nhân | 10% |
|:---:|:---:|
| Báo cáo    | 20% |
| Giữ kỳ     | 30% |
| Cuối kỳ    | 40% |


In [2]:
import numpy as np

def diemTrungBinh(a, b, c, d):
     return a * 0.1 + b * 0.2 + c * 0.3 + d * 0.4

diemSinhVien = np.array([[7, 8, 9, 5],
                        [8, 7, 4, 6],
                        [7, 5, 8, 6],
                        [6, 8, 5, 4],
                        [9, 9, 8, 7],
                        [10, 8, 9, 8]])

tenSinhVien = np.array(['A', 'B', 'C', 'D', 'E', 'F'])

for i in range(6):
    res = diemTrungBinh(*diemSinhVien[i])
    if res >= 5.0:
        print(f"Sinh viên {tenSinhVien[i]} có điểm là {round(res, 3)} và có kết quả: Đạt")
    else:
        print(f"Sinh viên {tenSinhVien[i]} có điểm là {round(res, 3)} và có kết quả: Không Đạt")

Sinh viên A có điểm là 7.0 và có kết quả: Đạt
Sinh viên B có điểm là 5.8 và có kết quả: Đạt
Sinh viên C có điểm là 6.5 và có kết quả: Đạt
Sinh viên D có điểm là 5.3 và có kết quả: Đạt
Sinh viên E có điểm là 7.9 và có kết quả: Đạt
Sinh viên F có điểm là 8.5 và có kết quả: Đạt


### Bài 2:
Sinh ngẫu nhiên ra 2 ma trận kích thước 3 x 3 và có các phần từ nguyên từ 0 đến 10

a) Tính tổng phần tử của mỗi ma trận

b) So sánh norm của vector hàng 1 và vector hàng 3 của hai ma trận

c) Tìm ma trận C, D, E là tổng, hiệu, tích, của hai ma trận trên

gợi ý: sử dụng lệnh np.randoom.radint(?, size = (?, ?))

In [32]:
mat1 = np.random.randint(0,10,size=(3,3))
mat2 = np.random.randint(0,10,size=(3,3))
print(matrix1)
print()
print(matrix2)

[[8 9 2]
 [3 5 8]
 [2 4 2]]

[[4 4 7]
 [5 9 9]
 [0 7 9]]


In [33]:
#a) tính tổng các phần tử của mỗi ma trận
def sumMatrix(list):
    tong = 0
    for i in list:
        tong += i
    return sum(tong)
sum1= summatrix(mat1)
sum2= summatrix(mat2)
print(f"tong cua cac phan tu trong matrix1 la: {sum1}")
print(f"tong cua cac phan tu trong matrix2 la: {sum2}")

tong cua cac phan tu trong matrix1 la: 36
tong cua cac phan tu trong matrix2 la: 42


In [34]:
#b) So sánh norm của vector hàng 1 và vector hàng 3 của hai ma trận
normRow_11 = np.linalg.norm(matrix1[0])
normRow_13 = np.linalg.norm(matrix1[2])
normRow_21 = np.linalg.norm(matrix2[0])
normRow_23 = np.linalg.norm(matrix2[2])
print(f"norm cua vector hang 1 cua matrix1 la: {normRow_11}")
print(f"norm cua vector hang 3 cua matrix1 la: {normRow_13}")
print(f"norm cua vector hang 1 cua matrix2 la: {normRow_21}")
print(f"norm cua vector hang 3 cua matrix2 la: {normRow_23}")
# Ham so sanh
def compare(a,b):
    if a > b:
        print("norm cua vector hang 1 lon hon norm cua vector hang 3")
    elif a == b:
        print("norm cua vector hang 1 bang norm cua vector hang 3")
    elif a < b:
        print("norm cua vector hang 1 nho hon norm cua vector hang 3")

print("Ket qua so sanh cua mat1")
compare(normRow_11,normRow_13)
print("Ket qua so sanh cua mat2")
compare(normRow_21,normRow_23)

norm cua vector hang 1 cua matrix1 la: 12.206555615733702
norm cua vector hang 3 cua matrix1 la: 4.898979485566356
norm cua vector hang 1 cua matrix2 la: 9.0
norm cua vector hang 3 cua matrix2 la: 11.40175425099138
Ket qua so sanh cua mat1
norm cua vector hang 1 lon hon norm cua vector hang 3
Ket qua so sanh cua mat2
norm cua vector hang 1 nho hon norm cua vector hang 3


In [47]:
#c) Tìm ma trận C, D, E là tổng, hiệu, tích, của hai ma trận trên
print(f"Tong cua matrix1 va matrix2 la:")
print(mat1+mat2)
print(f"Hieu cua matrix1 va matrix2 la:")
print(mat1-mat2)
print(f"Tich cua matrix1 va matrix2 la:")
print(mat1.dot(mat2))

Tong cua matrix1 va matrix2 la:
[[10 16 10]
 [12 10 10]
 [ 2  5  3]]
Hieu cua matrix1 va matrix2 la:
[[-4  0 -6]
 [ 2  4 -4]
 [ 0  3 -1]]
Tich cua matrix1 va matrix2 la:
[[ 63  50  84]
 [ 87  80 111]
 [ 28  21  38]]


### Bài Tập 3 Hãy dùng lệnh để sinh ra vector độ dài 21 với các phần tử từ a đến b nào đó. Chẳng hạn: 

a = 0, b = 100 hoặc a = 10.5, b = 50.

a) Dùng lệnh split, chia nhỏ vector kia ra thành 3 vector con, đặt là u, v, w.

b) Tính u*v và v.dot(w)

c) Tính shape của u trước và sau khi transpose, nhận xét.

*Gợi ý: lệnh np.linspace(a, b, c) với a, b là các số thực và c là số nguyên dương cho biết 
số phần tử cách đều nhau trong [a;b]*

In [3]:
vector = np.linspace(10.5,100,21)
print(vector)

[ 10.5    14.975  19.45   23.925  28.4    32.875  37.35   41.825  46.3
  50.775  55.25   59.725  64.2    68.675  73.15   77.625  82.1    86.575
  91.05   95.525 100.   ]


In [4]:
#a) Dùng lệnh split, chia nhỏ vector kia ra thành 3 vector con, đặt là u, v, w.
u , v, w = np.split(vector,[7,14])
print(u)
print(v)
print(w)

[10.5   14.975 19.45  23.925 28.4   32.875 37.35 ]
[41.825 46.3   50.775 55.25  59.725 64.2   68.675]
[ 73.15   77.625  82.1    86.575  91.05   95.525 100.   ]


In [5]:
#b) Tính u*v và v.dot(w)
print("Ket qua cua u*v la: ")
print(u*v)
print("Ket qua cua v.dot(w) la: ")
print(v.dot(w))

Ket qua cua u*v la: 
[ 439.1625   693.3425   987.57375 1321.85625 1696.19    2110.575
 2565.01125]
Ket qua cua v.dot(w) la: 
34043.59874999999


In [6]:
#c)Tính shape của u trước và sau khi transpose, nhận xét.
print("Shape cua u truoc khi transpose la: ",u.shape)
u1 = u.reshape((u.shape[0], 1))
print("Shape cua u sau khi transpose la: ",u1.shape)
'''Trước khi transpose, vector có kích thước (7,) tượng trưng cho vector hàng với 7 phần tử. Sau khi transpose, vector có kích thước (7, 1) biểu thị vector cột với 7 hàng và 1 cột.'''

Shape cua u truoc khi transpose la:  (7,)
Shape cua u sau khi transpose la:  (7, 1)


'Trước khi transpose, vector có kích thước (7,) tượng trưng cho vector hàng với 7 phần tử. Sau khi transpose, vector có kích thước (7, 1) biểu thị vector cột với 7 hàng và 1 cột.'

In [8]:
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"]
thu_tu = [2, 3, 4, 1]
diem_so = [10, 9, 8, 7]
anh_xa = zip(thu_tu, mon_hoc, diem_so)
print(list(anh_xa))

[(2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8), (1, 'LaptrinhCB', 7)]


\begin{split}\mathbf{A}=\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \ a_{21} & a_{22} & \cdots & a_{2n} \ \vdots & \vdots & \ddots & \vdots \ a_{m1} & a_{m2} & \cdots & a_{mn} \ \end{bmatrix}.\end{split}