# Đề thi Giữa kỳ Đại số tuyến tính cho Khoa học dữ liệu
## Khoa CNTT - trường ĐH Công nghiệp.
### Nhóm thực hành 1 & 2. Ngày 01/04/2022. Thời gian làm bài: 15h30' - 17h15'.

In [1]:
import numpy as np
from sympy import *

## Bài 1. (4 điểm)
Cho hai ma trận sau đây

$$A=\left( \begin{matrix}
   1 & 0 & 2 & a  \\
   1 & 2 & 4 & b  \\
   -1 & 2 & 0 & c  \\
   3 & -1 & 3 & d  \\
\end{matrix} \right), B=\left( \begin{matrix}
   4 & 5 & 1 & -2  \\
   0 & 1 & 2 & 1  \\
   0 & -2 & -3 & 1  \\
   a & b & c & d  \\
\end{matrix} \right)$$
trong đó $a,b,c,d$ là $4$ số cuối trong $MSSV$ (viết theo thứ tự từ trái sang phải). Khi làm bài, $SV$ chủ động thay các mã số đó vào đề bài trên.

Bằng cách dùng các thư viện có hỗ trợ sẵn của Python, hãy thực hiện các yêu cầu sau:
* a) Tính $B+A$, $B{{A}^{T}}$, $2A-3B$.
* b) Tính $\det (A)$ , $\det ({{B}^{T}}+2I)$, $rank(AB).$ 
* c) Tính norm của vector hàng $1$ của $A,$ tính norm của vector cột $3$ của $B,$ tính tổng các phần tử trên đường chéo của $A.$
* d) Kiểm tra công thức ${{(AB)}^{T}}={{B}^{T}}{{A}^{T}}$ dựa trên hai ma trận đã cho.
* e) Kiểm tra công thức $det(AB) = det(A)det(B)$ dựa trên hai ma trận đã cho.
* f) Sinh ngẫu nhiên một ma trận $C$ có kích thước $4\times 4$ với các phần tử là số nguyên trong miền từ $-9\to 9$, từ đó in ra các phần tử nằm phía dưới đường chéo của $A+BC.$ 

In [2]:
A = np.matrix([[1, 0, 2, 5], [1, 2, 4, 3], [-1, 2, 0, 9], [3, -1, 3, 1]])
B = np.matrix([[4, 5, 1, -2], [0, 1, 2, 1], [0, -2, -3, 1], [5, 3, 9, 1]])

In [3]:
# a.
B+A

matrix([[ 5,  5,  3,  3],
        [ 1,  3,  6,  4],
        [-1,  0, -3, 10],
        [ 8,  2, 12,  2]])

In [4]:
B@A.T

matrix([[ -4,  12, -12,   8],
        [  9,  13,  11,   6],
        [ -1, -13,   5,  -6],
        [ 28,  50,  10,  40]])

In [5]:
2*A-3*B

matrix([[-10, -15,   1,  16],
        [  2,   1,   2,   3],
        [ -2,  10,   9,  15],
        [ -9, -11, -21,  -1]])

In [6]:
# b.
#  det(A)
np.linalg.det(A)

64.00000000000003

In [29]:
np.linalg.det(B.T + 2*np.identity(B.shape[0]))

-237.99999999999986

In [30]:
np.linalg.matrix_rank(A@B)

4

In [32]:
# c.
#  norm của vector hàng  1  của  𝐴
np.linalg.norm(A[0])

5.477225575051661

In [33]:
# norm của vector cột  3  của  𝐵
np.linalg.norm(B[:, 2])

9.746794344808963

In [34]:
#tổng các phần tử trên đường chéo của  𝐴.
np.trace(A)

4

In [39]:
# d.
# (𝐴𝐵)𝑇
(A@B).T == B.T@A.T

matrix([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [40]:
# e.
round(np.linalg.det(A@B), 3) == round(np.linalg.det(A)*np.linalg.det(B), 3)

True

In [42]:
# f.
C = np.random.randint(-9, 10, size=(4, 4))
C

array([[-4, -3, -8,  9],
       [-6,  7,  3, -6],
       [ 5,  2,  9, -5],
       [ 3, -4, -4, -9]])

In [46]:
np.tril((A + B@C)[:-1, :-1])

array([[-46,   0,   0],
       [  8,   9,   0],
       [ -1, -22, -37]])

## Bài 2. (2 điểm)
Kết quả học tập của một nhóm sinh viên ở môn Đại số tuyến tính cho Khoa học dữ liệu được cho trong bảng bên dưới. Sinh viên chỉ qua môn nếu điểm tổng kết không dưới $5.0$.

|Sinh viên | BT cá nhân  | Báo cáo   | Giữa kỳ   | Cuối kỳ   |
|----------|-------------|-----------|-----------|-----------|
|  A       |     8       |    7      |    6      |    4      |
|  B       |     0       |    7      |    5      |    6      |
|  C       |     3       |    9      |    4      |    5      |
|  D       |     7       |    8      |    3      |    5      |
|  E       |     10      |    10     |    10     |    9      |
|  F       |     6       |    0      |    6      |    5      |

Giảng viên đang cân nhắc cho các điểm theo trọng số nào để có lợi cho các sinh viên nhất (ít người rớt nhất), có $3$ phương án:
* $0.2, 0.2, 0.2, 0.4$.
* $0.1, 0.1, 0.3, 0.5.$
* $0.1, 0.2, 0.3, 0.4.$

Hãy giúp giảng viên lựa chọn phương án thích hợp.

In [136]:
T = np.array([[0.2, 0.2, 0.2, 0.4], [0.1, 0.1, 0.3, 0.5], [0.1, 0.2, 0.3, 0.4]])
M = np.array([[8, 7, 6, 4], [0, 7, 5, 6], [3, 9, 4, 5], [7, 8, 3, 5], [10, 10, 10, 9], [6, 0, 6, 5]]).transpose()

In [137]:
# đếm só học sinh không qua cho mỗi phương án
check = ((T@M) < 5)
check.sum(axis=1)

array([2, 3, 1])

Từ các số ở trên ta thấy phương án 3 là phương án thích hợp nhất

## Bài 3. (2  điểm)
Cho bài toán sau, hãy bằng cách lập hệ phương trình thích hợp và giải bằng Python theo **ít nhất $2$ cách khác nhau**: <br>

Trong đợt dịch cúm Covid-19, sinh viên của một trường Đại học có nhận được trợ cấp từ nhà trường, từ địa phương và từ hội cựu sinh viên. Khảo sát trong một lớp học có ba nhóm: đang ở quê, đang ở trọ tại TPHCM và đang ở KTX trường. Biết rằng mức tiền hỗ trợ tiền:
* Của trường cho các nhóm trên lần lượt là: $200k, 600k, 400k$; 
* Của địa phương là: $500k, 500k, 500k$; 
* Của hội cựu sinh viên là: $0k, 700k, 300k.$

Biết rằng tổng tiền mà sinh viên được từ nhà trường là $21$ triệu, từ địa phương là $50$ triệu và từ hội cựu sinh viên là $32$ triệu. Tính tổng sinh viên của lớp.

In [152]:
# C1:
T = np.array([[200, 600, 400, 37000], [500, 500, 500, 50000], [0, 700, 300, 29000]])
x = np.array([Symbol('x{:d}'.format(i)) for i in range(3)])
t = np.hstack((x, -1))

In [157]:
kq = solve(T.dot(t))
values = list(kq.values())
np.sum(values)

100

In [158]:
# C2:
T1 = np.matrix([[200, 600, 400], [500, 500, 500], [0, 700, 300]])
b1 = np.array([37000, 50000, 29000])

In [159]:
round((T1.I).dot(b1).sum(), 2)

100.0

Vậy có tổng cộng 100 sinh viên

## Bài 4. (2 điểm)
Cho ma trận: $M=\left( \begin{matrix}
   2 & a & -2  \\
   0 & 3 & 0  \\
   0 & 0 & 3  \\
\end{matrix} \right)$ trong đó $a$ là tham số thực.
* a) Cho $a=1,$ hãy chéo hóa ma trận này để thu được ma trận $D$ bằng cách dùng thư viện của Python và kiểm chứng lại bằng việc tính toán từng bước để tìm đa thức đặc trưng và các giá trị riêng của $M$. Từ đó hãy nêu cách tính ${{M}^{99}}$.
* b) Ma trận chéo hóa $D$ của $M$ luôn không đổi với mọi giá trị $a$ tùy ý, hãy kiểm chứng với vài giá trị cụ thể của $a$ và giải thích lý do.


In [142]:
# a.
a = 1
M = np.matrix([[2, a, -2], [0, 3, 0], [0, 0, 3]])

In [143]:
D, P = np.linalg.eigh(M)
D = np.diag(D)
P = np.matrix(P)

Ma trận đương chéo các trị riêng $D$ là:

In [144]:
Matrix(D)

Matrix([
[2.0, 0.0, 0.0],
[0.0, 3.0, 0.0],
[0.0, 0.0, 3.0]])

### Tính tay:
Ta có: $Mv = \lambda v$<br>
$-> (M-\lambda I)v = 0$ <br>
Từ đó ta có: $det(M - \lambda I) = 0$

In [145]:
lamb = Symbol('lambda')
M1 = Matrix(M - lamb*np.identity(3))

Đa thức đặc trưng của M là:

In [146]:
M1.det()

-1.0*lambda**3 + 8.0*lambda**2 - 21.0*lambda + 18

Các trị riêng là:

In [147]:
solve(M1.det())

[2.00000000000000, 3.00000000000000]

Ta có: $M = PDP^{-1} \rightarrow M^{99}=PD^{99}P^{-1}$

In [148]:
M99 = P@np.power(D, 99)@P.I

Ma trận $M^{99}$ là:

In [149]:
Matrix(M99)

Matrix([
[6.33825300114115e+29,                 0.0,                 0.0],
[                 0.0, 1.7179250691067e+47,                 0.0],
[                 0.0,                 0.0, 1.7179250691067e+47]])

In [162]:
# b.
M2 = lambda a: np.matrix([[2, a, -2], [0, 3, 0], [0, 0, 3]])

In [167]:
# Với a = 2:
D, P = np.linalg.eigh(M2(2))
D

array([2., 3., 3.])

In [169]:
# Với a = 3:
D, P = np.linalg.eigh(M2(3))
D

array([2., 3., 3.])

In [170]:
# Với a = 4
D, P = np.linalg.eigh(M2(4))
D

array([2., 3., 3.])

Ta thấy các trị riêng không thay đổi khi thay $a$

In [171]:
a = Symbol('a')
M2 = Matrix([[2, a, -2], [0, 3, 0], [0, 0, 3]])
M2

Matrix([
[2, a, -2],
[0, 3,  0],
[0, 0,  3]])

In [172]:
(M2-lamb*np.identity(3)).det() 

-1.0*lambda**3 + 8.0*lambda**2 - 21.0*lambda + 18

Ta dễ dàng nhận thấy $a$ không nằm trong phương trình đặc trưng

### Giải thích: 
Ma trận $M$ là ma trận tam giác trên nên $det(M)$ sẽ bằng tích của các phần tử nằm trên đường chéo chính, từ đó $det(M - \lambda I)$ cũng sẽ bằng tích tích của các phần tử nằm trên đường chéo chính, mà $a$ không nằm trên đường chéo chính nên sẽ không ảnh hưởng đến các trị riêng của $M$ $\rightarrow$ ma trận đường chéo $D$ của $M$ luôn không đôi với mọi $a$ tùy ý  