## Câu 1:

Sinh viên hãy viết chương trình bằng Python hoặc sử dụng thư viện numpy/sympy để:

**a.** Tự chọn một ma trận khả nghịch 3x3. Sinh viên chứng minh ma trận đó khả nghịch (tồn
tại ma trận nghịch đảo)

**b.** Nhập họ và tên hoặc mã số sinh viên (của sinh viên).

**c.** Mã hóa họ và tên hoặc mã số sinh viên (của sinh viên).

**d.** Thực hiện giải mã với ma trận được chọn.

In [18]:
import numpy as np

In [21]:
# a) Tự chọn một ma trận khả nghịch 3x3. Sinh viên chứng minh ma trận đó khả nghịch (tồn tại ma trận nghịch đảo)
def generate_invertible_matrix():
    while True:
        m = np.random.randint(0, 10, (3, 3))
        if np.linalg.det(matrix) != 0:
            return m

matrix = generate_invertible_matrix()
linalg_Matrix = np.linalg.inv(matrix)
print(matrix, linalg_Matrix, sep = '\n\n')

[[1 4 9]
 [9 1 3]
 [0 9 0]]

[[-0.03846154  0.11538462  0.0042735 ]
 [ 0.          0.          0.11111111]
 [ 0.11538462 -0.01282051 -0.04985755]]


In [31]:
# b) Nhập họ và tên hoặc mã số sinh viên (của sinh viên).
input_name_id = input("Ho va ten hoac MSSV: ")

# Bảng mã
table_encoded = {' ': 5, 'D': 11, 'I': 17, 'Ơ': 23, 'T': 29, 'U': 30, 'A': 6, 'Đ': 12, 'K': 18, 'Ô': 24,
                 'Ă': 7, 'E': 13, 'L': 19, 'P': 25, 'Ư': 31, 'Â': 8, 'Ê': 14, 'M': 20, 'Q': 26, 'V': 32,
                 'B': 9, 'G': 15, 'N': 21, 'R': 27, 'X': 33, 'C': 10, 'H': 16, 'O': 22, 'S': 28, 'Y': 34,
                 '‘': 0, '`': 1, '?': 2, '~': 3, '.': 4}

# Chuyển đổi thông tin thành chuỗi số tương ứng
num_string = []
for char in input_name_id:
    if char in table_encoded:
        num_string.append(table_encoded[char])
    else:
        print("Kí tự '{}' không được hỗ trợ và sẽ bị bỏ qua.".format(char))

print("Chuỗi số tương ứng là: ", num_string)

# Bước c: Mã hóa họ và tên hoặc mã số sinh viên
encoded_info = []
for num in num_string:
    encoded_num = num + matrix[num % 3, num % 3]  # Thêm giá trị mã vào từng phần tử
    if encoded_num > 34:  # Xoay vòng nếu giá trị vượt quá 34
        encoded_num -= 35
    encoded_info.append(encoded_num)
print("Chuỗi số đã được mã hóa: ", encoded_info)

# Bước d: Thực hiện giải mã với ma trận được chọn
decoded_info = []
for encoded_num in encoded_info:
    decoded_num = encoded_num - matrix[encoded_num % 3, encoded_num % 3]  # Trừ đi giá trị mã từng phần tử
    if decoded_num < 0:  # Xoay vòng nếu giá trị nhỏ hơn 0
        decoded_num += 35
    decoded_info.append(decoded_num)
print("Chuỗi số đã được giải mã: ", decoded_info)


Ho va ten hoac MSSV:  TAN TAI


Chuỗi số tương ứng là:  [29, 6, 21, 5, 29, 6, 17]
Chuỗi số đã được mã hóa:  [29, 7, 22, 5, 29, 7, 17]
Chuỗi số đã được giải mã:  [29, 6, 21, 5, 29, 6, 17]


## Câu 2:
Với một phân số $\frac{p_n}{q_n}$$$$$được biểu diễn dưới dạng liên phân số như sau:
$$\frac{p_n}{q_n} = c_0 + \frac{1}{c_1+\frac{1}{c_2+...+\frac{1}{c_n}}}$$
Người ta chứng minh được rằng có một cách xác định $𝑝_𝑛$ và $𝑞_𝑛$ như sau:
$$\left(\begin{matrix}c_0&1\\1&0\end{matrix}\right)\left(\begin{matrix}c_1&1\\1&0\end{matrix}\right)...\left(\begin{matrix}c_n&1\\1&0\end{matrix}\right)=\left(\begin{matrix}p_n&q_{n-1}\\q_n&q_{n-1}\end{matrix}\right),n=0,1,2,...$$
a. Xây dựng chương trình tính 𝑝𝑛 và 𝑞𝑛 khi có danh sách 𝑛 giá trị $𝑐_0$, $𝑐_1$, … , $𝑐_𝑛$.

b. Hãy chứng minh điều trên.


In [ ]:
import numpy as np
import random

In [39]:
# Tạo danh sách ngẫu nhiên 
def generate_random_list(n, a, b):
  return [random.randint(a, b) for _ in range(n)]

# Tạo ma trận từ danh sách
def create_matrix(lst):
  return [np.array([[x, 1], [1, 0]]) for x in lst]

# Nhân ma trận  
def multiply(matrices):
  result = None
  for m in matrices:
    result = np.dot(result, m) if result is not None else m
  return result

# Lấy kết quả
def get_pn_qn(matrices):
  result = multiply(matrices)  
  return result[0,0], result[1,0]


n = int(input("Nhập n: "))

a = generate_random_list(n, 0, 20) 
print("Danh sách ngẫu nhiên: ", a)

m = create_matrix(a)
print("Ma trận tạo từ danh sách: ", m, sep = '\n')
p_n, q_n = get_pn_qn(m)
print(f"Kết quả: p_n = {p_n}, q_n = {q_n}")

Nhập n:  20


Danh sách ngẫu nhiên:  [19, 13, 7, 14, 20, 4, 10, 19, 9, 4, 16, 4, 13, 7, 15, 0, 6, 11, 3, 17]
Ma trận tạo từ danh sách: 
[array([[19,  1],
       [ 1,  0]]), array([[13,  1],
       [ 1,  0]]), array([[7, 1],
       [1, 0]]), array([[14,  1],
       [ 1,  0]]), array([[20,  1],
       [ 1,  0]]), array([[4, 1],
       [1, 0]]), array([[10,  1],
       [ 1,  0]]), array([[19,  1],
       [ 1,  0]]), array([[9, 1],
       [1, 0]]), array([[4, 1],
       [1, 0]]), array([[16,  1],
       [ 1,  0]]), array([[4, 1],
       [1, 0]]), array([[13,  1],
       [ 1,  0]]), array([[7, 1],
       [1, 0]]), array([[15,  1],
       [ 1,  0]]), array([[0, 1],
       [1, 0]]), array([[6, 1],
       [1, 0]]), array([[11,  1],
       [ 1,  0]]), array([[3, 1],
       [1, 0]]), array([[17,  1],
       [ 1,  0]])]
Kết quả: p_n = -1565660313, q_n = -208151265


Để chứng minh điều trên, chúng ta có thể sử dụng phương pháp quy nạp. Đặt ma trận được nhân là A và giả sử biểu thức trên đúng với n = k:

\$[ A_k = \begin{bmatrix} c_k & 1 \\ 1 & 0 \end{bmatrix} \begin{bmatrix} c_{k-1} & 1 \\ 1 & 0 \end{bmatrix} \dotsm \begin{bmatrix} c_1 & 1 \\ 1 & 0 \end{bmatrix} = \begin{bmatrix} p_k & p_{k-1} \\ q_k & q_{k-1} \end{bmatrix} \]$

Bây giờ, chúng ta sẽ chứng minh biểu thức cho n = k + 1:

\$[ A_{k+1} = \begin{bmatrix} c_{k+1} & 1 \\ 1 & 0 \end{bmatrix} \begin{bmatrix} p_k & p_{k-1} \\ q_k & q_{k-1} \end{bmatrix} \]$

\$[ A_{k+1} = \begin{bmatrix} c_{k+1}p_k + p_{k-1} & c_{k+1}p_{k-1} + p_k \\ c_{k+1}q_k + q_{k-1} & c_{k+1}q_{k-1} + q_k \end{bmatrix} \]$

Từ giả sử, chúng ta biết rằng \$( A_k = \begin{bmatrix} p_k & p_{k-1} \\ q_k & q_{k-1} \end{bmatrix} \)$. Đặt \$( p_{k+1} = c_{k+1}p_k + p_{k-1} \$) và \$( q_{k+1} = c_{k+1}q_k + q_{k-1} \$), chúng ta có thể thấy rằng \$( A_{k+1} = \begin{bmatrix} p_{k+1} & p_k \\ q_{k+1} & q_k \end{bmatrix} \$).

Do đó, biểu thức trên đúng với mọi n bằng cách sử dụng quy nạp.
dụng quy nạp.
 \) bằng cách sử dụng quy nạp.
dụng quy nạp.
