# ĐỀ KIỂM TRA THƯỜNG KỲ 1
## Môn: Đại số tuyến tính tính toán
## Ngày: 01/03/2024
## Lớp: DHKHDL18A - Nhóm TH1 & TH2. Thời gian: 90 phút
## Họ tên: Phan Tấn Tài - MSSV: 22684181

**Câu 1.** (3 điểm) Cho hai ma trận $A$ và $B$ xác định như sau $$A=\begin{bmatrix} 2 & 3 & -1\\0 & -3 & 1\\1&1&-1 \end{bmatrix}, B = \begin{bmatrix} 0 & 3 & -3\\-1 & 2 & 0\\-4&4&1 \end{bmatrix}.$$

a) Tính $AB$, $BA^T$ và $rank(AB)$.

b) Ma trận $BA$ là ma trận suy biến hay không? Tại sao?

c) Tìm tất cả các ma trận xác định dương $C$ cấp $3$ thoả mãn $BC=BAC^{2024}+C^T$.

In [17]:
import numpy as np

A = np.array([[2, 3, -1], [0, -3, 1],[1, 1, -1]])
B = np.array([[0, 3, -3], [-1, 2, 0], [-4, 4, 1]])

print(A,B, sep = '\n\n')

print("Câu a)")
AB = np.dot(A,B)
print(f"AB = {AB}")
A_T = np.transpose(A)
BA_T = np.dot(B, A_T)
print(f"B(A^T) = {BA_T}")

rank_of_AB = np.linalg.matrix_rank(AB)

print(f"Hạng của ma trận AB = {rank_of_AB}")

[[ 2  3 -1]
 [ 0 -3  1]
 [ 1  1 -1]]

[[ 0  3 -3]
 [-1  2  0]
 [-4  4  1]]
Câu a)
AB = [[ 1  8 -7]
 [-1 -2  1]
 [ 3  1 -4]]
B(A^T) = [[ 12 -12   6]
 [  4  -6   1]
 [  3 -11  -1]]
Hạng của ma trận AB = 3


In [18]:
print("Câu b)")

BA = np.dot(B,A)
det_BA = np.linalg.det(BA)
print(f"Giá trị của định thức ma trận BA = {det_BA}")

Câu b)
Giá trị của định thức ma trận BA = -36.0


Ma trận BA không là một ma trận suy biến bởi vì giá trị định thức DET(BA) = -36 khác 0 nên không thể là một ma trận suy biến

In [ ]:
print("Câu c)")

**Câu 2.** (2 điểm) Một đoàn xe tải chở $290$ tấn xi măng cho một công trình xây đập thuỷ điện. Đoàn xe gồm $57$ chiếc gồm $3$ loại: xe chở $3$ tấn, xe chở $5$ tấn và xe chở $7.5$ tấn. Nếu dùng tất cả xe chở $7.5$ tấn chở ba chuyến thì được số xi măng bằng tổng số xi măng do xe $5$ tấn chở ba chuyến và xe $3$ tấn chở hai chuyến. 

a) Gọi $x_1,x_2,x_3$ lần lượt là số xe tải chở $3$, $5$ và $7.5$ tấn và đặt $X=\begin{bmatrix} x_1 & x_2 & x_3 \end{bmatrix}^T$. Mô hình hoá bài toán trên dưới dạng hệ phương trình tuyến tính $AX=b$, bằng cách tìm $A$ và $b$.

b) Tính số xe mỗi loại bằng ít nhất hai cách.


### Lời giải
***a)***
ta có tổng số xi măng mà 3 xe phải chở là: $$3x_1 + 5x_2 + 7.5x_3 = 290 ~~~(1)$$ 
Tổng số xe cần sử dụng cho để chở hàng là : $$x_1 + x_2 + x_3 = 57 ~~~(2)$$
Nếu dùng tất cả xe chở $7.5$ tấn chở ba chuyến thì được số xi măng bằng tổng số xi măng do xe $5$ tấn chở ba chuyến và xe $3$ tấn chở hai chuyến  là: $$6x_1 + 15x_2 = 22.5x_3 ~~~(3)$$
từ $(1),(2)$ và $(3)$ ta có hệ phương trình : 

\begin{cases}
3x_1 + 5x_2 + 7.5x_3 = 290 \\
x_1 + x_2 + x_3 = 57 \\
6x_1 + 15x_2 - 22.5x_3 = 0
\end{cases} 
vậy phương trình tuyến tính có dạng $Ax = b$ là :

$$\begin{bmatrix}
3& 5& 7.5\\
1  &1  &1\\
6  &15  &-22.5\\
\end{bmatrix} \begin{bmatrix} x_1\\x_2\\x_3 \end{bmatrix}
= \begin{bmatrix} 290\\57\\0 \end{bmatrix}$$

In [19]:
import numpy as np

A = np.array([[3, 5, 7.5], [1, 1, 1], [6, 15, -22.5]])
b = np.array([290, 57, 0])
res1 = np.linalg.solve(A, b)
res2 = np.linalg.inv(A)@b
print("Câu b)")
print(f"Kết quả tính số xe theo cách số 1")
print(f"Số xe 1: {res1[0]}")
print(f"Số xe 2: {res1[1]}")
print(f"Số xe 3: {res1[2]}")

print(f"Kết quả tính số xe theo cách số 2")
print(f"Số xe 1: {round(res2[0])}")
print(f"Số xe 2: {round(res2[1])}")
print(f"Số xe 3: {round(res2[2])}")

Câu b)
Kết quả tính số xe theo cách số 1
Số xe 1: 20.0
Số xe 2: 19.0
Số xe 3: 18.0
Kết quả tính số xe theo cách số 2
Số xe 1: 20
Số xe 2: 19
Số xe 3: 18


### Giải thích các cách tính ở ý b câu 2
**Cách 1**
Em sử dụng phương thức có sẵn trong numpy là np.linalg.solve() để giải hệ phương trình trên

**Cách 2**
Em sử dung phương thức np.linalg.inv() để tìm ma trận nghịch đảo của A. Sau đó em biến đổi lại công thức $Ax=B$ $=>$ $x = A^-1 * b$ và tính kết quả dựa theo phương trình đã biến đổi

**Câu 3.** (3 điểm) Cho ma trận $A$ được xác định bởi $$A=\begin{bmatrix} 
1 & 1 & 2\\
2 & -1 & 1\\
-2 & 4 & 1
\end{bmatrix}.$$
Tìm hai ma trận $Q$ và $R$ thoả mãn $A=QR$, biết $Q$ là ma trận gồm các vector cột trực chuẩn và $R$ là ma trận tam giác trên khả nghịch. Sinh viên tính toán theo từng bước dưới đây và sau đó dùng thư viện thích hợp để kiểm tra lại.

**Bước 1.** Các vector cột của $A$ là:
$$u_1 = [1,2,-2 ]^T, \, u_2 = [ 1, -1, 4]^T, \, u_3 = [ 2,1 ,1 ]^T.$$

**Bước 2.** Trực giao hóa họ các vector bằng thuật giải Gram-Schmidt (để thuận tiện, ta viết vector theo dòng)

$$v_1 = u_1 = (1, 2, -2),$$
$$\left\| v_1 \right\|^2 = 9, $$
$$\left\langle u_2,v_1 \right\rangle = -9,$$
$$v_2 = u_2 - \frac{\left\langle u_2,v_1 \right\rangle}{\left\| v_1 \right\|^2} v_1 = (2, 1, 2)$$
$$\left\| v_2 \right\|^2 = 9, $$
$$\left\langle u_3,v_1 \right\rangle = 2,$$
$$\left\langle u_3,v_2 \right\rangle = 7,$$
$$v_3 = u_3 - \frac{\left\langle u_3,v_1 \right\rangle}{\left\| v_1 \right\|^2} v_1 - \frac{\left\langle u_3,v_2 \right\rangle}{\left\| v_2 \right\|^2} v_2 = (\frac{2}{9} \frac{-2}{9}, \frac{1}{9}),$$
$$\left\| v_3 \right\|^2 = \frac{-2}{9}, $$
Kết luận họ trực giao là:
$$v_1 = (1, 2, -2), v_2 = (2, 1, 2), v_3 = (\frac{2}{9} \frac{-2}{9}, \frac{1}{9}).$$

**Bước 3.** Tìm ma trận $Q$: chuẩn hóa họ các vector ở trên, ta được
$$q_1 = \frac{v_1}{\left\| v_1 \right\|} = \frac{1}{3}(1, 2, -2),$$
$$q_2 = \frac{v_2}{\left\| v_2 \right\|} = \frac{1}{3}(2, 1, 2),$$
$$q_3 = \frac{v_3}{\left\| v_3 \right\|} = \frac{1}{3}(2, -2, 1).$$
Từ đó có ma trận $Q$ là:
$$Q=\left[ \begin{matrix}
   {{q}_{1}} & {{q}_{2}} & {{q}_{3}}  \\
\end{matrix} \right]=\frac{1}{3} \left[ \begin{matrix}
   {1} & {2} & {2}  \\
   {2} & {1} & {-2}  \\
   {-2} & {2} & {1}  \\
\end{matrix} \right]$$

**Bước 4.** Tìm ma trận $R$: ta tính các tích vô hướng sau đây
$$\left\langle {{u}_{1}},{{q}_{1}} \right\rangle = -3, $$
$$\left\langle {{u}_{2}},{{q}_{1}} \right\rangle = 3, $$
$$\left\langle {{u}_{3}},{{q}_{1}} \right\rangle = \frac{-2}{3}, $$
$$\left\langle {{u}_{2}},{{q}_{2}} \right\rangle = -3$$
$$\left\langle {{u}_{3}},{{q}_{2}} \right\rangle = \frac{-7}{3}, $$
$$\left\langle {{u}_{3}},{{q}_{3}} \right\rangle = \frac{1}{3} $$
Từ đó ta có ma trận $R$ là:

$$R=\left[ \begin{matrix}
   \left\langle {{u}_{1}},{{q}_{1}} \right\rangle  & \left\langle {{u}_{2}},{{q}_{1}} \right\rangle  & \left\langle {{u}_{3}},{{q}_{1}} \right\rangle   \\
   0 & \left\langle {{u}_{2}},{{q}_{2}} \right\rangle  & \left\langle {{u}_{3}},{{q}_{2}} \right\rangle   \\
   0 & 0 & \left\langle {{u}_{3}},{{q}_{3}} \right\rangle   \\
\end{matrix} \right]=\left[ \begin{matrix}
   {-3} & {3} & {\frac{-2}{3} }  \\
   {0} & {-3} & {\frac{-7}{3} }  \\
   {0} & {0} & {\frac{-1}{3}}  \\
\end{matrix} \right]$$

In [20]:
# Dùng thư viên thích hợp kiểm tra
import numpy as np

A = np.array([[1,1,2], [2, -1, 1], [-2, 4, 1]])  
Q, R = np.linalg.qr(A)
print(f"Ma trận Q (sau khi được làm tròn 6 chữ số thập phân sau dấu phải)\n{np.round(Q,decimals = 6)}")
print()
print(f"Ma trận R (sau khi được làm tròn 6 chữ số thập phân sau dấu phải)\n{np.round(R,decimals = 6)}")
print("Ta tính được ma trận QR = ")
print(Q@R)

Ma trận Q (sau khi được làm tròn 6 chữ số thập phân sau dấu phải)
[[-0.333333 -0.666667  0.666667]
 [-0.666667 -0.333333 -0.666667]
 [ 0.666667 -0.666667 -0.333333]]

Ma trận R (sau khi được làm tròn 6 chữ số thập phân sau dấu phải)
[[-3.        3.       -0.666667]
 [ 0.       -3.       -2.333333]
 [ 0.        0.        0.333333]]
Ta tính được ma trận QR = 
[[ 1.  1.  2.]
 [ 2. -1.  1.]
 [-2.  4.  1.]]


Dễ dàng thấy được ma trận $QR$ $=$ $A$ ban đầu

**Vậy các bước kiểm tra trên đã thoả mãn yêu cầu bài toán**

**Câu 4.** (2 điểm) Cho $A$ là ma trận vuông cấp $2$ có hai giá trị riêng là $1$ và $-2$, với hai vector riêng tương ứng là $(1,0)$ và $(1,-1)$.

a) Tìm $A^{2024}$.

b) Tìm các giá trị riêng của $A^{2024}$.

In [16]:
import numpy as np

A = np.array([[1,0], [0, -2]])

a) Để tính $A^{2024}$, ta có công thức:

$$A = PDP^{-1}$$

Với $P$ là ma trận đối xứng của $A$ và $D$ là tham trị riêng

$$A^{2024} = PD^{2024}P^{-1}$$



## --------------------------------------- Hết --------------------------------------

### Lưu ý: sinh viên không được sử dụng internet. Giám thị không giải thích gì thêm.